[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[dependencies]
forge-std = "1.9.4"
"@openzeppelin-contracts" = "5.1.0"

[soldeer]
remappings_generate = true
remappings_regenerate = false
remappings_version = true
remappings_prefix = ""
remappings_location = "txt"

recursive_deps = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
